import type { Framework } from "./detect.js";

// Full coval_tracing.py reference — extracted from CLI traces.rs
export const COVAL_TRACING_PY_REFERENCE = `# coval_tracing.py — generated by coval wizard
#
# This module configures OpenTelemetry tracing for Coval evaluation.
# Call setup_coval_tracing() at startup or when a new call/session begins,
# then set_simulation_id() when the Coval simulation ID arrives (typically
# via SIP header or env var).
#
# Spans are buffered until set_simulation_id() is called, so no spans
# are lost even if tracing is initialized before the call connects.
#
# Prefer Coval span naming conventions for the richest UI and metric support:
#   llm           — LLM inference spans
#   tts           — Text-to-speech spans
#   stt           — Speech-to-text spans
#   llm_tool_call — Tool/function call spans
#
# See: https://docs.coval.dev/traces

import logging
import os
import threading
from collections import deque
from contextvars import ContextVar
from typing import Deque, Dict, Optional, Sequence
from uuid import uuid4

from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import ReadableSpan, Span, SpanProcessor, TracerProvider
from opentelemetry.sdk.trace.export import SimpleSpanProcessor, SpanExporter, SpanExportResult

logger = logging.getLogger("coval_tracing")

COVAL_API_KEY = os.environ.get("COVAL_API_KEY", "")
COVAL_TRACES_ENDPOINT = "https://api.coval.dev/v1/traces"
MAX_PREACTIVATION_BUFFER = 1024

_INTERNAL_SIMULATION_ID_ATTR = "coval.internal.simulation_id"
_INTERNAL_BUFFER_KEY_ATTR = "coval.internal.buffer_key"

_router: Optional["_ContextualCovalExporter"] = None
_current_simulation_id: ContextVar[Optional[str]] = ContextVar(
    "coval_simulation_id", default=None
)
_current_buffer_key: ContextVar[Optional[str]] = ContextVar(
    "coval_buffer_key", default=None
)

# ── Span renamer ─────────────────────────────────────────────────────────────
# Remaps span names from framework conventions to Coval conventions on start.

_SPAN_NAME_MAP = {
    "llm_request": "llm",
    "llm_request_run": "llm",
    "tts_request": "tts",
    "tts_request_run": "tts",
    "stt_request": "stt",
    "stt_request_run": "stt",
}


class _CovalSpanRenamer(SpanProcessor):
    """Renames spans on start to match Coval conventions."""

    def on_start(self, span: Span, parent_context=None) -> None:
        name = span.name
        if name in _SPAN_NAME_MAP:
            span._name = _SPAN_NAME_MAP[name]
        elif name.startswith("function_call"):
            span._name = "llm_tool_call"
        simulation_id = _current_simulation_id.get()
        if simulation_id:
            span.set_attribute(_INTERNAL_SIMULATION_ID_ATTR, simulation_id)
        buffer_key = _current_buffer_key.get()
        if buffer_key:
            span.set_attribute(_INTERNAL_BUFFER_KEY_ATTR, buffer_key)

    def on_end(self, span: ReadableSpan) -> None:
        pass

    def shutdown(self) -> None:
        pass

    def force_flush(self, timeout_millis: int = 30000) -> bool:
        return True


# ── Contextual exporter ──────────────────────────────────────────────────────

class _ContextualCovalExporter(SpanExporter):
    """Routes spans to simulation-specific exporters and bounded buffers."""

    def __init__(self, api_key: str):
        self._api_key = api_key
        self._lock = threading.RLock()
        self._exporters: Dict[str, OTLPSpanExporter] = {}
        self._buffers: Dict[str, Deque[ReadableSpan]] = {}

    def _get_or_create_exporter(self, simulation_id: str) -> OTLPSpanExporter:
        exporter = self._exporters.get(simulation_id)
        if exporter is None:
            exporter = OTLPSpanExporter(
                endpoint=COVAL_TRACES_ENDPOINT,
                headers={
                    "x-api-key": self._api_key,
                    "X-Simulation-Id": simulation_id,
                },
                timeout=30,
            )
            self._exporters[simulation_id] = exporter
        return exporter

    def _buffer_for_key(self, buffer_key: str) -> Deque[ReadableSpan]:
        buffer = self._buffers.get(buffer_key)
        if buffer is None:
            buffer = deque(maxlen=MAX_PREACTIVATION_BUFFER)
            self._buffers[buffer_key] = buffer
        return buffer

    def activate(self, simulation_id: str, buffer_key: Optional[str]) -> None:
        """Start exporting spans with the given simulation ID."""
        with self._lock:
            exporter = self._get_or_create_exporter(simulation_id)
            buffered = list(self._buffers.pop(buffer_key, ())) if buffer_key else []
        if buffered:
            logger.info(
                "Flushing %d buffered spans to Coval for simulation_id=%s",
                len(buffered),
                simulation_id,
            )
            exporter.export(buffered)

    def export(self, spans: Sequence[ReadableSpan]) -> SpanExportResult:
        dropped = 0
        batches = []
        with self._lock:
            grouped: Dict[str, list[ReadableSpan]] = {}
            for span in spans:
                attributes = span.attributes or {}
                simulation_id = attributes.get(_INTERNAL_SIMULATION_ID_ATTR)
                if simulation_id:
                    grouped.setdefault(str(simulation_id), []).append(span)
                    continue

                buffer_key = str(
                    attributes.get(_INTERNAL_BUFFER_KEY_ATTR)
                    or _current_buffer_key.get()
                    or "default"
                )
                buffer = self._buffer_for_key(buffer_key)
                before = len(buffer)
                buffer.append(span)
                if before == MAX_PREACTIVATION_BUFFER:
                    dropped += 1

            for simulation_id, batch in grouped.items():
                batches.append((self._get_or_create_exporter(simulation_id), batch))

        if dropped:
            logger.warning(
                "Dropped %d oldest buffered span(s) before simulation ID activation",
                dropped,
            )

        for exporter, batch in batches:
            result = exporter.export(batch)
            if result is not SpanExportResult.SUCCESS:
                return result
        return SpanExportResult.SUCCESS

    def force_flush(self, timeout_millis: int = 30000) -> bool:
        with self._lock:
            exporters = list(self._exporters.values())
        return all(exporter.force_flush(timeout_millis) for exporter in exporters)

    def shutdown(self) -> None:
        with self._lock:
            exporters = list(self._exporters.values())
            self._exporters.clear()
            self._buffers.clear()
        for exporter in exporters:
            exporter.shutdown()


# ── Public API ───────────────────────────────────────────────────────────────

def _begin_tracing_context() -> str:
    buffer_key = uuid4().hex
    _current_buffer_key.set(buffer_key)
    _current_simulation_id.set(None)
    return buffer_key


def setup_coval_tracing(service_name: str = "coval-agent") -> None:
    """Initialize OpenTelemetry tracing for Coval.

    Call at startup or when a new call/session begins. Spans are buffered until
    set_simulation_id() is called. If COVAL_API_KEY is not set, tracing is
    disabled and a warning is logged.
    """
    global _router
    if not COVAL_API_KEY:
        logger.warning("COVAL_API_KEY not set — tracing disabled")
        return
    if _router is None:
        _router = _ContextualCovalExporter(api_key=COVAL_API_KEY)
        resource = Resource.create({SERVICE_NAME: service_name})
        provider = TracerProvider(resource=resource)
        provider.add_span_processor(_CovalSpanRenamer())
        provider.add_span_processor(SimpleSpanProcessor(_router))
        trace.set_tracer_provider(provider)
        logger.info("Coval tracing initialized — waiting for simulation ID")
    else:
        logger.info("Coval tracing reset — waiting for simulation ID")
    _begin_tracing_context()


def set_simulation_id(simulation_id: str) -> None:
    """Activate trace export with the given simulation ID.

    Typically called when the Coval simulation ID arrives via SIP header
    (X-Coval-Simulation-Id) or environment variable (COVAL_SIMULATION_ID).
    """
    if _router and simulation_id:
        buffer_key = _current_buffer_key.get() or _begin_tracing_context()
        _current_simulation_id.set(simulation_id)
        _router.activate(simulation_id, buffer_key)
        logger.info("Coval tracing active for simulation_id=%s", simulation_id)


# ── LiveKit session instrumentation ──────────────────────────────────────────
# Call instrument_session(session) after AgentSession.start() to hook events
# that create Coval-compatible spans for STT, tool calls, and TTFB metrics.

def instrument_session(session) -> None:
    """Hook AgentSession events to create Coval trace spans.

    Must be called after session.start(). Hooks:
    - user_input_transcribed -> creates "stt" spans with transcript attribute
    - function_tools_executed -> creates "llm_tool_call" spans
    - metrics_collected -> creates spans with metrics.ttfb attribute
    """
    tracer = trace.get_tracer("coval.instrumentation")

    def _on_user_input_transcribed(event):
        if not getattr(event, "is_final", False):
            return
        with tracer.start_as_current_span("stt") as span:
            span.set_attribute("transcript", event.transcript or "")

    def _on_function_tools_executed(event):
        for call in getattr(event, "function_calls", []):
            with tracer.start_as_current_span("llm_tool_call") as span:
                span.set_attribute("function.name", getattr(call, "name", ""))
                span.set_attribute("tool_call_id", getattr(call, "call_id", ""))
                span.set_attribute("function.arguments", getattr(call, "arguments", ""))

    def _on_metrics_collected(event):
        metrics = getattr(event, "metrics", None)
        if metrics is None:
            return
        metrics_type = getattr(metrics, "type", "")
        ttfb = getattr(metrics, "ttfb", None)
        if ttfb is None:
            return
        if metrics_type == "llm_metrics":
            span_name = "llm"
        elif metrics_type == "stt_metrics":
            span_name = "stt"
        elif metrics_type == "tts_metrics":
            span_name = "tts"
        else:
            return
        with tracer.start_as_current_span(span_name) as span:
            span.set_attribute("metrics.ttfb", ttfb)

    session.on("user_input_transcribed", _on_user_input_transcribed)
    session.on("function_tools_executed", _on_function_tools_executed)
    session.on("metrics_collected", _on_metrics_collected)
    logger.info("Coval session instrumentation active")


# ── Utility functions for non-LiveKit frameworks ─────────────────────────────

def create_llm_span(input_text: str = "", model: str = "", **kwargs):
    """Create an LLM span. Use as a context manager: with create_llm_span(...) as span: ..."""
    tracer = trace.get_tracer("coval.instrumentation")
    span = tracer.start_span("llm")
    if input_text:
        span.set_attribute("input", input_text)
    if model:
        span.set_attribute("gen_ai.request.model", model)
    for k, v in kwargs.items():
        span.set_attribute(k, v)
    return trace.use_span(span, end_on_exit=True)


def create_stt_span(transcript: str = "", **kwargs):
    """Create an STT span. Use as a context manager."""
    tracer = trace.get_tracer("coval.instrumentation")
    span = tracer.start_span("stt")
    if transcript:
        span.set_attribute("transcript", transcript)
    for k, v in kwargs.items():
        span.set_attribute(k, v)
    return trace.use_span(span, end_on_exit=True)


def create_tts_span(**kwargs):
    """Create a TTS span. Use as a context manager."""
    tracer = trace.get_tracer("coval.instrumentation")
    span = tracer.start_span("tts")
    for k, v in kwargs.items():
        span.set_attribute(k, v)
    return trace.use_span(span, end_on_exit=True)


def create_tool_call_span(name: str = "", call_id: str = "", arguments: str = "", **kwargs):
    """Create a tool call span. Use as a context manager."""
    tracer = trace.get_tracer("coval.instrumentation")
    span = tracer.start_span("llm_tool_call")
    if name:
        span.set_attribute("function.name", name)
    if call_id:
        span.set_attribute("tool_call_id", call_id)
    if arguments:
        span.set_attribute("function.arguments", arguments)
    for k, v in kwargs.items():
        span.set_attribute(k, v)
    return trace.use_span(span, end_on_exit=True)
`;

const FRAMEWORK_RULES: Record<Framework, string> = {
  pipecat: `## Pipecat Framework Rules
- Inject \`setup_coval_tracing()\` BEFORE \`PipelineTask()\`, \`PipelineRunner()\`, or \`Pipeline()\` construction
- Extract the simulation ID from \`args.body\` in the \`on_dialin_connected\` handler if present:
  \`\`\`python
  sim_id = (args.body or {}).get("dialin_settings", {}).get("custom_context", {}).get("coval_simulation_id")
  if sim_id:
      set_simulation_id(sim_id)
  \`\`\`
- If there is NO \`on_dialin_connected\` handler, add a TODO comment for where to call \`set_simulation_id()\`
- Add \`enable_metrics=True\` and \`enable_tracing=True\` to PipelineTask if not already present`,

  livekit: `## LiveKit Agents Framework Rules
- Inject \`setup_coval_tracing()\` BEFORE \`AgentSession()\` or \`VoicePipelineAgent()\` construction
- Extract the simulation ID from the SIP participant attributes:
  \`\`\`python
  # In the entrypoint function, after session.start():
  async def _check_sim_id(participant):
      sim_id = participant.attributes.get("sip.h.X-Coval-Simulation-Id")
      if sim_id:
          set_simulation_id(sim_id)

  ctx.room.on("participant_connected", lambda p: asyncio.ensure_future(_check_sim_id(p)))
  ctx.room.on("participant_attributes_changed", lambda old, p: asyncio.ensure_future(_check_sim_id(p)))
  \`\`\`
- After \`await session.start()\`, add \`instrument_session(session)\` to hook STT/tool/metrics spans
- Import \`instrument_session\` from \`coval_tracing\` alongside \`setup_coval_tracing\` and \`set_simulation_id\``,

  generic: `## Generic Python Agent Rules
- Add \`setup_coval_tracing()\` at module level, after imports
- Add a TODO comment for where to call \`set_simulation_id()\` with the actual simulation ID
- If there's an obvious place where a session/call starts, suggest calling \`set_simulation_id()\` there`,
};

export function buildSystemPrompt(framework: Framework): string {
  return `You are an expert Python developer specializing in OpenTelemetry instrumentation.
Your task is to add Coval tracing to a user's AI agent codebase.

## Reference Implementation
Below is the complete \`coval_tracing.py\` module that you MUST use as-is. Do NOT modify its contents.
Generate this file exactly as shown:

\`\`\`python
${COVAL_TRACING_PY_REFERENCE}
\`\`\`

${FRAMEWORK_RULES[framework]}

## Output Format
Return ONLY valid JSON with these exact keys:
{
  "coval_tracing_py": "<the complete coval_tracing.py file content>",
  "modified_entry_point": "<the complete modified entry point file>",
  "explanation": "<1-3 sentence explanation of what was changed>"
}

## Rules
- Preserve ALL existing code — only ADD imports and setup calls
- Produce the minimal diff possible
- NEVER hardcode API keys — always use environment variables
- Add \`# COVAL:\` comment markers next to injected lines
- The \`coval_tracing.py\` content must be IDENTICAL to the reference above
- Import from \`coval_tracing\`: \`setup_coval_tracing\`, \`set_simulation_id\`, and \`instrument_session\` (LiveKit only)`;
}

export function buildUserPrompt(opts: {
  framework: Framework;
  entryPointPath: string;
  entryPointContent: string;
  additionalFiles: Record<string, string>;
}): string {
  let prompt = `Add Coval tracing to this ${opts.framework} agent project.

Entry point file (${opts.entryPointPath}):
\`\`\`python
${opts.entryPointContent}
\`\`\``;

  for (const [name, content] of Object.entries(opts.additionalFiles)) {
    prompt += `\n\n${name}:\n\`\`\`\n${content}\n\`\`\``;
  }

  return prompt;
}
